import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { NAVIGATION_ITEMS } from "./config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frank Hartman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <Navbar items={NAVIGATION_ITEMS} />
        {children}
      </body>
    </html>
  );
}
